---
- name: Configure network devices
  hosts: all
  gather_facts: no
  tasks:
    - name: Configure hostname
      shell: echo {{ inventory_hostname }} > /etc/hostname && hostname {{ inventory_hostname }}
    - name: Configure IP address
      command: ip addr add {{ ip_address }} dev eth0
    - name: Bring up interface
      command: ip link set eth0 up

